export const SET_ADD_ITEM_MODAL = 'SET_ADD_ITEM_MODAL'
export const SET_ADD_BUTTONS_MODAL = 'SET_ADD_BUTTONS_MODAL'
export const SET_PRO_MODAL_SHOW = 'SET_PRO_MODAL_SHOW'
export const SET_IMAGE_BROWSER_MODAL_SHOW = 'SET_IMAGE_BROWSER_MODAL_SHOW'
export const SET_WARDROBE_TYPE = "SET_WARDROBE_TYPE"

export const ADD_ITEM = "ADD_ITEM"
export const SET_TRANSFER_IMAGE = 'SET_TRANSFER_IMAGE'
export const SET_CURRENT_ITEM = 'SET_CURRENT_ITEM'
export const EDIT_ITEM = 'EDIT_ITEM'
export const SET_ASSOCIATED_ITEM = 'SET_ASSOCIATED_ITEM'
export const DELETE_ITEM = "DELETE_ITEM"

export const SET_CURRENT_WARDROBE_TAB = "SET_CURRENT_WARDROBE_TAB"
export const SET_CURRENT_ASSOCIATED_CATEGORY = "SET_CURRENT_ASSOCIATED_CATEGORY"
export const SET_ASSOCIATED_CATEGORY_HISTORY = "SET_ASSOCIATED_CATEGORY_HISTORY"

export const SET_ACTIVE_LOOK_CATEGORY = "SET_ACTIVE_LOOK_CATEGORY"

export const SET_BUY_PRO = "SET_BUY_PRO"